### ISSUE TITLE
Some glob patterns don't work, sucking up CPU

### ISSUE THREAD

**Issue by avaragado** [zinserjan/mocha-webpack#27] opened 2016-06-30 11:20 UTC
I have two top-level directories in a repository, called `src` and `lib`. Both have tests. I want to run mocha-webpack with `--watch` to run those tests.

I have a `mocha-webpack.opts` file like this:

```
--colors
--include test/setup.js
--reporter spec
--webpack-config webpack/webpack.config.babel.js
{src,lib}/**/__test__/*.spec.js
```

and in package.json:

```
    "mocha": "NODE_ENV=test babel-node ./node_modules/.bin/mocha-webpack",
    "mocha:watch": "npm run mocha -- --watch",
```

(babel-node is used as I write my webpack config in ES6. It's not the cause of this issue, as I've verified the same thing occurs with an ES5 config.)

`npm run mocha` works fine. Sadly when i run `npm run mocha:watch` this results in a massive slowdown, some tests don't run, file changes aren't spotted, my fan spins up, dogs howl, etc.

The cause seems to be the leading braces in the file spec in mocha-webpack.opts.

```
src/**/__test__/*.spec.js  # ok
{src}/**/__test__/*.spec.js  # bad
```

Some debugging suggests the braces cause some part of the code to hunt through the entire repository, since the constant parent of the file spec glob is `.`. Naturally, this includes `node_modules`, and so everything grinds to a halt.

I'm working around this using a simple entry point file, based on your `prepareEntry.js` code. It's a little grubby but it works:

```js
const isWatch = process.argv.indexOf('--watch') > -1;

// This gets replaced by webpack with the updated files on rebuild
const __webpackManifest__ = []; // eslint-disable-line no-underscore-dangle

const isInManifest = path => __webpackManifest__.indexOf(path) >= 0;
const isAlways = () => true;

// // no, you really can't optimise this, as webpack needs to statically analyse the code.
const contexts = [
    require.context('../src', true, /__test__\/.*\.spec\.js/),
    require.context('../lib', true, /__test__\/.*\.spec\.js/),
];

const run = (testsContext) => {
    testsContext.keys()
    .filter(isWatch ? isInManifest : isAlways)
    .forEach(testsContext);
};

contexts.forEach(run);
```

I'm not sure if there's a better solution. Perhaps mocha-webpack could accept multiple filespecs and prepareEntry.js could output something like the above?

**Comment by zinserjan** [comment] 2016-07-07 17:28
> Some debugging suggests the braces cause some part of the code to hunt through the entire repository, since the constant parent of the file spec glob is .. Naturally, this includes node_modules, and so everything grinds to a halt.

Yep, that's the issue for high cpu load... The main problem is that webpack doesn't understand globs for require.context. As a workaround i have to detect the base directory of the provided glob, pass that directory and a fake regex as file pattern to require.context.

If there's a lib that translates glob pattern with fixed entry folders (e.g. `{src,lib}/**/*.js`) to multiple paths instead of single base directory, we could also consider this. 

>  Perhaps mocha-webpack could accept multiple filespecs and prepareEntry.js could output something like the above?

Yep, that's the plan. There is already an issue for this (#8).

Then you could write your `mocha-webpack.opts` like this:
```
--colors
--include test/setup.js
--reporter spec
--webpack-config webpack/webpack.config.babel.js
src/**/__test__/*.spec.js
lib/**/__test__/*.spec.js
```

> I'm working around this using a simple entry point file, based on your prepareEntry.js code. It's a little grubby but it works

That's the best solution for the moment.

**Comment by zinserjan** [comment] 2016-08-27 18:04
I found an option to stop webpack from watching node_modules. That could help with your slowdown, when the issue is really caused by the watcher. But I would expect that multiple entries are more performat. 

**webpack-config.test.js**
```javascript
module.exports = {
  ...
  watchOptions: {
    ignored: /node_modules/
  }.
  ...
};
```

Closing this in favour of #45

**Closed by zinserjan** 2016-08-27 18:04 UTC

**Comment by ethanensler** [comment] 2017-03-17 23:33
We also ran into this issue when we created a new project structure for our front-end code. We couldn't get around this issue by upgrading to the 1.0.0-beta because the beta version seemed to run our tests much more slowly, to the point where some of them were hitting a mocha timeout. While we could have simply made the timeout longer, we didn't feel comfortable putting the slower test runner into production. @zinserjan Any idea why the 1.0.0-beta might be significantly slower than 0.7.0?
A few other notes:
1) It seems that `watchOptions` is only available in Webpack 2. We're still using Webpack 1 in our project so this wasn't an option.
2) @avaragado, your code for creating an entry point with multiple require contexts did work for us, so thanks.
